### ISSUE TITLE
Exception happened when running on device

### ISSUE THREAD

**Issue by Zetazzz** [bradmartin/nativescript-audio#11]
Hi

This's a great plugin and it works great on emulators. But when I tried to deploy(the demo or an test app created by me) and play(remote and local both tried) on a Samsung device(N-7100, android 4.3), there's an exception:

com.tns.NativeScriptException: 
Calling js method onInfo failed

TypeError: Cannot read property 'msg' of undefined
File: "/data/data/org.nativescript.audio/files/app/main-view-model.js, line: 119, column: 50

StackTrace: 
Frame: function:'playerOptions.infoCallback', file:'/data/data/org.nativescript.audio/files/app/main-view-model.js', line: 119, column: 51
Frame: function:'_this.player.setOnInfoListener.MediaPlayer.OnInfoListener.onInfo', file:'/data/data/org.nativescript.audio/files/app/tns_modules/nativescript-audio/src/android/player.js', line: 45, column: 37

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
at com.tns.Runtime.callJSMethod(Runtime.java:712)
at com.tns.Runtime.callJSMethod(Runtime.java:693)
at com.tns.Runtime.callJSMethod(Runtime.java:683)
at com.tns.gen.android.media.MediaPlayer_OnInfoListener_ftns_modules_nativescript-audio_src_android_player_l43_c52__.onInfo(android.media.MediaPlayer$OnInfoListener.java)
at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2521)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5493)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
at dalvik.system.NativeStart.main(Native Method)

Please kindly take a look and tell me if there's any work around...
Thank you very much!!

**Comment by Zetazzz** [comment]
Hi

Found the issue


                infoCallback: (info) => {
                    console.log("what: " + info);
                }

the 'info' could be undefined, so info.msg may throw the exception.

Thanks any way
