### ISSUE TITLE
tns build android is failing - :asbg:generateBinding

### ISSUE THREAD

**Issue by matterhornsolutions** [bradmartin/nativescript-audio#48]
When I build for android, I get the following error: 

```
Running full build
finished with reading lines with js files
Warning: there already is an extend called com.tns.NativeScriptActivity.
Warning: there already is an extend called com.tns.FragmentClass.
:asbg:generateBindings

Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
<project_folder>/platforms/android/src/main/java/com/tns/gen/android/content/BroadcastReceiver_frnal_ts_helpers_l58_c38__BroadcastReceiver.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:60)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '<project_folder>/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 251

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

I've done some googling but not getting anywhere. 

I then grepped my project for those two classes and found twice: once in node_modules/tns-core-modules and again in nativescript-audio's node_modules/tns-core-modules dependency. 

How is the Android compiler supposed to reconcile this? I didn't have a problem building for iOS. 

Also, using v2.5.4. Any thoughts are appreciated. Thanks.

**Comment by matterhornsolutions** [comment]
I believe this was caused by a version mismatch in tns-core-modules in the two locations. Upgraded the whole project to latest and the build works. Thanks.
