### ISSUE TITLE
Build android app fail

### ISSUE THREAD

**Issue by garynhs** [bradmartin/nativescript-audio#50]
HI,

I build an Android application with 3.3.0 and everything work fine. When i upgrade to 3.4.2, I got the following error.

```
:asbg:generateBindings
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
/Users/gary/Documents/ma288/ma288-radio/platforms/android/src/main/java/com/tns/gen/android/content/BroadcastReceiver_frnal_ts_helpers_l58_c38__BroadcastReceiver.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:60)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/gary/Documents/ma288/ma288-radio/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 251

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.036 secs
Command /Users/gary/Documents/ma288/ma288-radio/platforms/android/gradlew failed with exit code 1

```

**Comment by bradmartin** [comment]
I believe that error has come up previously on other issues when there is a mismatch in some dependencies and the core-modules. I'd recommend checking your package.json and nuking the platform folders, then running a new build.

**Comment by garynhs** [comment]
Yes, it should the problem. Thanks a lot
