### ISSUE TITLE
v3.4.2 fail on Android

### ISSUE THREAD

**Issue by conekeo** [bradmartin/nativescript-audio#51]
Hi,

It's working on IOS, but the app crash on Android v3.4.2 

Error:
```JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'release' of undefined
JS: TypeError: Cannot read property 'release' of undefined
JS:     at file:///data/data/com.ugroupmedia.pnp.client.mobile/files/app/tns_modules/nativescript-audio/src/android/player.js:203:29
JS:     at new ZoneAwarePromise (file:///data/data/com.ugroupmedia.pnp.client.mobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:776:29)
JS:     at TNSPlayer.dispose (file:///data/data/com.ugroupmedia.pnp.client.mobile/files/app/tns_modules/nativescript-audio/src/android/player.js:201:16)
```

it's the dispose() method  that seems to fail on Android:
here my code

 ```
 this._player.dispose().then(() => {
                this._player.initFromUrl({
                    audioFile: callUrl, 
                    loop: false,
                    completeCallback: this._trackComplete.bind(this),
                    errorCallback: this._trackError.bind(this),
                }).then(() => {
                    this._player.getAudioTrackDuration().then((duration) => {
                        this._player.play();
                    });
                });
            });

```

**Comment by NathanWalker** [comment]
Fixed in `3.4.3` 👍
