### ISSUE TITLE
Exception when starting app in android device

### ISSUE THREAD

**Issue by madsongr** [bradmartin/nativescript-audio#74]
Following [this](https://bradmartin.net/2016/05/03/recording-audio-in-a-nativescript-app) tutorial I got the exception below after when I open the app in android real device:

`
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.AudioRecorder/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-audio", relative to: app/tns_modules/
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
	at android.app.ActivityThread.access$800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5001)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.Na
`

It didn´t even ask permission for RECORD_AUDIO

**Comment by madsongr** [comment]
I solved by creating a new project with sidekick and adding the plugin manually to package.json. It should have cli issues.
